### ISSUE TITLE
https page requests returned as http

### ISSUE THREAD

**Issue by rosselet** [brix-cms/brix-cms#145]
We have a site that is running under Brix, without any pages marked as either requiresSSL or requiresNonSSL.  Whenever we attempt to access with https://  protocol, the resulting page returned is http://  
Is this expected behaviour?  Are we missing a configuration somewhere?  In brix 1.2.2-snapshot, the admin site was at least available in https. but using 1.3.0-snapshot (built aug 29/2011) we also get switched to http protocol.

Is this a wicket or a brix config problem?  Anyone else encountered this? We are running on glassfish 3.1 appserver

**Comment by kbachl** [comment]
should already be fixed by current wicket 8 changes;
