### ISSUE TITLE
Build problems with JDK 8 - dep: FELIX-4005

### ISSUE THREAD

**Issue by kbachl** [brix-cms/brix-cms#182]
on doing 

mvn clean build

it can fail by: 

[ERROR] Error building bundle org.brixcms:brix-plugin-menu:bundle:8.0-SNAPSHOT : Invalid class file: org/brixcms/plugin/menu/editor/MenuEditor$1.class

reason is that the used 

<groupId>org.apache.felix</groupId>
<artifactId>maven-bundle-plugin</artifactId>

is not compatible with mvn 3 and java 8, see 
https://issues.apache.org/jira/browse/FELIX-4005
and
https://issues.apache.org/jira/browse/FELIX-4882

-> All 
<groupId>org.apache.felix</groupId>
<artifactId>maven-bundle-plugin</artifactId>
<version>2.x.x</version>

have to be upgraded to

<groupId>org.apache.felix</groupId>
<artifactId>maven-bundle-plugin</artifactId>
<version>3.2.0</version>

for continuing function;

Remark: this is for me to remember - will fix in in the next days

**Comment by dsimko** [comment]
Do you have latest version of the master branch? I commented out these plugins in this commit - https://github.com/brix-cms/brix-cms/pull/180/commits/a530b39061c451efb6882f5704f1f38bbddf713e
But I don't know if we still need these plugins? I haven't been interested in OSGI yet..

**Comment by kbachl** [comment]
I did it with the master exactly before marting commited it; However, the OSGI was in the past important to some brix users and thats the reason we left it in (since it also didnt add any cost or problems); The idea and wish at the time also was that one day brix may get the ability to deploy and undeploy plugins and tiles-packages on the fly and that this can be done with OSGI easily.... I think @briantopping even used it in real worl somehow;

I would let these in for the time beeing and the fix is really just getting all versions to 3.2.0 - was a typical JDK 8 bug/problem.
