### ISSUE TITLE
allow pages to be shown under (root) path / index.brix feature

### ISSUE THREAD

**Issue by kbachl** [brix-cms/brix-cms#184]
currently if you open e.g.: mydomain.com brix will redirect to mydomain.com/somepage 

instead of doing so there has to be a way to display a default page on the root path so that no redirect happens and instead the content of a page will be displayed under the path;

to make it impossible for pages to be aligned to it without desire the page shown there can be hardcoded as "index.brix"; so in any directory where a file is located with the name "index.brix" the content will be shown under the root path; direct access from outside on that index.brix path on the other hand is prohibuted and ends up in and 404; this is important for SEO reasons as else you end up having duplicate content of the important pages

e.g.:

domain.com/ -> displays "index.brix" without any trace to it in either AJAX nor regular requests
domain.com/index.brix -> displays 404 and doesnt load the page

**Comment by dsimko** [comment]
Maybe for root path it could be solved quite easily by adding (here [1]) something like this:

            final BrixNode node = getNodeForUriPath(path);
            if(node.hasNode("index.brix")){
                node = node.getNode("index.brix");
            }


And UriMapper [2] could also be helpful.
        
[1] https://github.com/brix-cms/brix-cms/blob/master/brix-core/src/main/java/org/brixcms/web/BrixRequestMapper.java#L110
[2] https://github.com/brix-cms/brix-cms/blob/master/brix-core/src/main/java/org/brixcms/config/UriMapper.java

**Comment by kbachl** [comment]
[1] wont work for subfolders then however - its my plan that this feature also works for all subfolders so its usable on all

i got this working with a branch of brix with wicket 1.4 as well as wicket 6 - so I think I can grab the details; especially the ajaxhandling needs also to be checked here as ajax requests went through different routes in the past;

**Comment by dsimko** [comment]
Yes, you are right. 
When I was working on something else I found out that probably the best place would be  [1]. And there should be something like this [2].
Anyway I am curious about your solution.

[1] https://github.com/brix-cms/brix-cms/blob/master/brix-core/src/main/java/org/brixcms/plugin/site/folder/FolderNodePlugin.java#L74
[2] https://github.com/brix-cms/brix-cms/blob/master/brix-core/src/main/java/org/brixcms/plugin/site/page/AbstractSitePagePlugin.java#L69

**Comment by kbachl** [comment]
ok, it seems the whole URL handling got really changed much between wicket 1.4 and 8 - also the implementation differs drastically from org. brix 1.4 times;

I've done a basic approach based on my working world and it works for root node so far; However, I got no luck on the link creation because If I even touch the mapper slightly it breaks too much and ends up with mach redirct problems....

you may want to have a look at my commit to my fork under 
https://github.com/kbachl/brix-cms/commit/8161276f89c7f5e0c6dbd0d497ec52c93b1e8dc0

Any Idea how we get link rewriting to work in the mapper?

**Comment by dsimko** [comment]
I played with it a little bit and it seems to work quite well. Please look at
https://github.com/dsimko/brix-cms/commit/d739f65cc843318b11e4dae80b0a19822536aa8f
If you want to try it please don't forget to clear "Redirect Reference" for folder on admin page.
But it is only draft I didn't have enough time to test it properly.

**Comment by kbachl** [comment]
Ahh, I see. We both have nearly identical ideas for the static String as well as the FolderNodePlugin (your solution lacks the redirect there in case the "/index.brix" gets called directly in browser -> duplicate content problem)

But your idea on the URL with the BrixRequestMapper is really neat.... seems I need to spend more time on that URL building from wicket 6+

**Comment by dsimko** [comment]
The redirect for direct "/index.brix" is here:
https://github.com/dsimko/brix-cms/commit/d739f65cc843318b11e4dae80b0a19822536aa8f#diff-706ea9d748e506020ab62a19cb2cb412R110

**Comment by kbachl** [comment]
ok, that didnt work yet; I've taken your code and used it onto a clean branch from current wicket 8 master; It seems that /index.brix works, but in a subfolder you get the same internal error than me;

plus the link building is alos not working; I've setup a demo with menu links to /index.brix and /test/index.brix and both links dont get rewritten

**Comment by kbachl** [comment]
the menu component uses the regual Reference from brix that links together pages (=jcr nodes) - need to have a look at that

**Comment by dsimko** [comment]
Could you please create a reproducer (e.g. export your workspace.xml and source of your tiles) so I could take a loot at it. Because all what you mentioned (subfolders, links, menu) had worked for me.

**Comment by kbachl** [comment]
I've mailed you the demo workspace-  i run it in the default demo, so nothing special here; I fixed at least the links in my commit https://github.com/kbachl/brix-cms/commit/5a494777f083b590a3c9a7d0fcdeaa7e8ec04d17

**Comment by dsimko** [comment]
Thank you. Subfolder didn't work because your Site/test/index.brix is empty. When you add some text to it (e.g. "hello") it should work. But you are right with menu links. This will need further investigation.

**Comment by kbachl** [comment]
hmmm.... but we do want to allow empty pages, don't we?

The Links work now (in my 2nd commit) - only thing I want to change is that they shall be absolute instead of relative ones;

The other things like 301 instead of 302 and so on will be added later - as this is quite simple to do (I intend to add 1 more field to the folder node that sets the redirect type: 302 or 301 with 302 beeing the default)

**Comment by dsimko** [comment]
>hmmm.... but we do want to allow empty pages, don't we?

I do not know. I don't see any use case for empty pages. But we should at least provide better info about what is wrong. Anyway this is not related to this issue since this happens for all pages. 

Why do you want absolute urls for menu links?

Adding possibility to choose between 301 and 302 sounds good to me.

**Comment by kbachl** [comment]
- empty pages use case: google, onpage.org and various crawler tools expect a hash-path that gets an empty content back; maybe this makes sense there - even that can be an empty page with some spaces in it... in any case we need a useful error message!

- absolute URLs are better for seo since often the folder-names contain keywords and therefore the page gets stuffed with that content (and this is a way that does zero harm to any page as its standard behaviour)

**Comment by martin-g** [comment]
* I didn't get what is the purpose of the empty pages. And I wasn't able to find anything at onpage.org.
 * Absolute urls are unfriendly to proxies

**Comment by kbachl** [comment]
@martin-g 

- I can live without empty pages - but not without correct warning / info about them.... at least showing an internal server error under the page path is *IMHO* the worst kind of way

- I dont know any proxy that has problems with absolute URLs, but I know the importance of SEO... anyway, we can make this optional even I dont know of any site who prefers the "might be problem of a proxy" over the negative SEO impact

**Comment by martin-g** [comment]
* I'm not sure I understand what "empty page" means to you/Brix but for me an empty page is not useful at all, so better no page at all. If someone requests something that is not there then error 404 should be returned.
* keywords in folder names have nothing to do with relative and absolute urls. Any relative url is resolved against the current url and made absolute at the client side. The client could be a browser, a bot, a command line tool, ...

**Comment by kbachl** [comment]
"empty page" = you create an page in the backend; at that time there is no content so it is "empty" = null valued
that is the initial state of every page before content gets added

if you now open up the page and it has no contet set we get an internal server error - that needs to be fixed

**Comment by martin-g** [comment]
:-)
This is a weird case, IMO.
You can also create a page with compilation errors or totally broken HTML. 
I don't expect such page to be production-ready, so I won't bother whether it breaks for me in DEV mode. And this page definitely won't be deployed at Production before being finished!

But it is your call if you want to spend your time on supporting this!

**Comment by kbachl** [comment]
@martin-g I dont think this is weird, this is against the behaviour brix had in the past! - if you look at the nodes you see that any BrixFileNode gets initialized as:

`public static BrixFileNode initialize(JcrNode node, String mimeType) {
        if (node.isNodeType("nt:file") == false) {
            throw new IllegalStateException("Argument 'node' must have JCR type nt:file.");
        } else if (node instanceof BrixFileNode) {
            return (BrixFileNode) node;
        }
        node.addNode("jcr:content", "nt:resource");
        BrixFileNode wrapped = new BrixFileNode(node.getDelegate(), node.getSession());
        wrapped.setMimeType(mimeType);
        wrapped.getContent().setProperty("jcr:lastModified", Calendar.getInstance());
        wrapped.getContent().setProperty("jcr:data", "");
        return wrapped;
    }`

where the content is set as empty string.... and this should be displayed by the page; however, this seems to not work at the moment and the trace goes through wicket itself... still digging in further

**Comment by martin-g** [comment]
Just created a fresh quickstart app with Wicket 8.0.0-SNAPSHOT and removed the whole content in HomePage.html, and commented out the single component in HomePage.java (`add(new Label("version", getApplication().getFrameworkSettings().getVersion()));`).
Trying to run it leads to:
```
Root cause:

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
     at java.util.ArrayList.rangeCheck(ArrayList.java:653)
     at java.util.ArrayList.get(ArrayList.java:429)
     at java.util.Collections$UnmodifiableList.get(Collections.java:1309)
     at org.apache.wicket.markup.Markup.get(Markup.java:126)
     at org.apache.wicket.Component.internalRender(Component.java:2372)
     at org.apache.wicket.Component.render(Component.java:2323)
     at org.apache.wicket.Page.renderPage(Page.java:987)
     at org.apache.wicket.request.handler.render.WebPageRenderer.renderPage(WebPageRenderer.java:124)
     at org.apache.wicket.request.handler.render.WebPageRenderer.respond(WebPageRenderer.java:236)
     at org.apache.wicket.core.request.handler.RenderPageRequestHandler.respond(RenderPageRequestHandler.java:175)
     at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:912)
     at org.apache.wicket.request.RequestHandlerExecutor.execute(RequestHandlerExecutor.java:65) 
     ...
```

As I said earlier I find it very weird to need to support an empty page! 
I see two options:
1) start a discussion at dev@wicket.apache.org about this requirement
2) set some dummy content in the node's data, e.g. `<html></html>` or `<!-- a comment -->`

**Comment by martin-g** [comment]
The `fix` in Wicket is as simple as:
````diff
diff --git i/wicket-core/src/main/java/org/apache/wicket/Component.java w/wicket-core/src/main/java/org/apache/wicket/Component.java
index 97262ed..7fd575c 100644
--- i/wicket-core/src/main/java/org/apache/wicket/Component.java
+++ w/wicket-core/src/main/java/org/apache/wicket/Component.java
@@ -2363,6 +2363,10 @@ public abstract class Component
                        throw new MarkupNotFoundException("Markup not found for Component: " + toString());
                }
 
+               if (markup.size() == 0) {
+                       return;
+               }
+
````

**Comment by kbachl** [comment]
@martin-g I know that its easy - its just that wicket 8 behaves different than 1.4 did - and I never checked wicket 1.5 till 7.x so I dont realy wanted to bugger the whole dev team....

Anyways, I will merge the index.brix feature now, only postponing the redirect state from 302 to 301; rest works, including AJAX on root :)

**Comment by kbachl** [comment]
closing this as feater is now merged // 302/301 choice is postponed
