### ISSUE TITLE
fix wicket versions?

### ISSUE THREAD

**Issue by kbachl** [brix-cms/brix-cms#206]
Hi,

can we change from the wicket snapshot versions to the milestones? That way we are somewhat more stable and things like https://github.com/brix-cms/brix-cms/commit/df7508b58fbe483e3d3c4aaba34334149ac51b5b don't get into the stream anymore?

This would allow us to also "fix" versions of brix at a certain milestone level

**Comment by kbachl** [comment]
todo: wait for wicket 8-m5 and then fix at that version and move on to milestones only

**Comment by kbachl** [comment]
@martin-g Martin, do you think a wicket 8.0.0-M7 is possible this weekend?
I desperately want to fix the version to release a brix milestone but due to the JSON problem wicket 8 M6 won't work

**Comment by martin-g** [comment]
This weekend - no!
What JSON problem with M6 ?

**Comment by kbachl** [comment]
https://issues.apache.org/jira/browse/WICKET-6400

this one was a nasty one for me in my own project; Also the change in the json library made it impossible to mix older and newer builds;

When do you expect a new milestone build?

**Comment by martin-g** [comment]
Wicket 8 uses openjson as Maven dependency.
So you can just declare the dependency with its latest version in your app and Wicket will use it.
For this you don't need to wait for new Wicket release.

**Comment by kbachl** [comment]
clsoing this issue as its outdated by latest commits
