### ISSUE TITLE
website is hacked

### ISSUE THREAD

**Issue by DanielRuf** [brix-cms/brix-cms#207]
@dsimko see the results at https://www.google.de/search?q=site%3Awww.brixcms.org and click them. Many redirect to other websites.

**Comment by kbachl** [comment]
the website brixcms.org is not affiliated to us, instead it is operated by a third party that never responded to any contact tries we made; Since it is registered by the use of an proxy registration ( Domains By Proxy, LLC ) I somehow am not really sorry about this....

**Comment by DanielRuf** [comment]
So why is it linked in the project description at the top?
