### ISSUE TITLE
weak password hashing algorithm

### ISSUE THREAD

**Issue by DanielRuf** [brix-cms/brix-cms#208]
The PasswordEncoder class uses SHA-1 (with a salt) which is not very strong.

https://github.com/brix-cms/brix-cms/blob/master/brix-rmiserver/src/main/java/org/brixcms/rmiserver/PasswordEncoder.java

Use bcrypt or better.

**Comment by kbachl** [comment]
rmiserver is not intended for production usage - it will be removed in future revisions as the RMI idea behind never worked at a scalable level

**Comment by DanielRuf** [comment]
Bump.
