### ISSUE TITLE
NPE after session expires

### ISSUE THREAD

**Issue by briantopping** [brix-cms/brix-cms#52]
What steps will reproduce the problem? 1. Open admin console 2. Expire
session (I put my laptop to sleep and got on the train) 3. Click a link
This looks like a Wicket bug, but I don't have Wicket sources loaded to
provide a patch. Maybe this is fixed already. What is the expected
output? What do you see instead? From the logs: ERROR - RequestCycle -
java.lang.NullPointerException at
java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:768)
at
org.apache.wicket.protocol.http.pagestore.DiskPageStore.getSessionEntry(DiskPageStore.java:661)
at
org.apache.wicket.protocol.http.pagestore.DiskPageStore.containsPage(DiskPageStore.java:1255)
at
org.apache.wicket.protocol.http.SecondLevelCacheSessionStore$SecondLevelCachePageMap.containsPage(SecondLevelCacheSessionStore.java:268)
at org.apache.wicket.Session.getPage(Session.java:662) at
org.apache.wicket.request.target.coding.HybridUrlCodingStrategy.decode(HybridUrlCodingStrategy.java:211)
at
org.apache.wicket.protocol.http.request.WebRequestCodingStrategy.targetForRequest(WebRequestCodingStrategy.java:491)
at
org.apache.wicket.protocol.http.WebRequestCycleProcessor.resolve(WebRequestCycleProcessor.java:184)
at org.apache.wicket.RequestCycle.step(RequestCycle.java:1252) at
org.apache.wicket.RequestCycle.steps(RequestCycle.java:1370) at
org.apache.wicket.RequestCycle.request(RequestCycle.java:501) at
org.apache.wicket.protocol.http.WicketFilter.doGet(WicketFilter.java:455)
at
org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:288)
What version of the product are you using? On what operating system?
Brix r495, wicket-1.4-20090119.081010-334. Please provide any additional
information below.

**Comment by kbachl** [comment]
not reproduce / very old
