### ISSUE TITLE
Incorrect inheritance in JcrNode

### ISSUE THREAD

**Issue by briantopping** [brix-cms/brix-cms#65]
<b>Creator</b> - chris@tty.nl

What steps will reproduce the problem? 1. Use JcrNode in source code 2.
View it using IntelliJ IDEA 3. It complains that jcrNode.getPath()
throws an exception. What is the expected output? What do you see
instead? \* There should not be a warning about throwing the exception.
Please provide any additional information below: \* Changing the
'extends' order fixes the issue: change: public interface JcrNode
extends Node, JcrItem into : public interface JcrNode extends JcrItem,
Node

**Comment by kbachl** [comment]
CannotReproduce
