### ISSUE TITLE
Relative links do not render properly at depth

### ISSUE THREAD

**Issue by briantopping** [brix-cms/brix-cms#97]
<b>Creator</b> - brian.topping

Given a site with three levels of depth "/->B->C", some relative
references work and some do not. A file at root level (/index.html) with
relative reference to a file in level B works, but a file at level B
with relative reference to level C does not. In B/index.html, a link is
in the source as "C/target.html". The link is incorrectly rendered as
"../C/target.html", causing the problem. B/index.html uses a template of
/templates/base.html. It's unclear if that is having an effect.

**Comment by kbachl** [comment]
CannotReproduce
